@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package systems.thedawn.espresso.datagen;

import javax.annotation.ParametersAreNonnullByDefault;

import net.minecraft.MethodsReturnNonnullByDefault;