@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package systems.thedawn.espresso;

import javax.annotation.ParametersAreNonnullByDefault;

import net.minecraft.MethodsReturnNonnullByDefault;