@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package systems.thedawn.espresso.drink;

import javax.annotation.ParametersAreNonnullByDefault;

import net.minecraft.MethodsReturnNonnullByDefault;